import org.gradle.jvm.toolchain.JavaLanguageVersion

plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
    id("com.github.ben-manes.versions") version "0.54.0"
}

group = 'net.amygdalum'
description = 'A fluent API for allotropy'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }

    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
    mavenLocal()
}

sourceSets {
    examples {
        java {
            compileClasspath += main.output + test.output
            runtimeClasspath += main.output + test.output
            srcDirs = [file('src/examples/java')]
        }
        resources {
            srcDirs = [file('src/examples/resources')]
        }
    }
}

configurations.named("examplesImplementation") {
    extendsFrom configurations.testImplementation
}

dependencies {
    api 'org.assertj:assertj-core:3.27.3'
    api 'org.seleniumhq.selenium:selenium-java:4.33.0'

    testImplementation 'io.github.bonigarcia:webdrivermanager:6.1.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.12.2'
    testImplementation 'org.junit.platform:junit-platform-engine:1.12.2'
    testImplementation 'org.junit.platform:junit-platform-launcher:1.12.2'
    testImplementation 'io.undertow:undertow-core:2.3.18.Final'
    testImplementation 'ch.qos.logback:logback-classic:1.5.18'
    testImplementation 'org.slf4j:jul-to-slf4j:2.0.17'
    
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.12.2'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes(
            'Automatic-Module-Name': 'net.amygdalum.allotropy.fluent'
        )
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            
	        pom {
		        name = 'Fluent-Allotropy'
		        description = 'A Fluent Assertion Framework for Allotropy (Testing Responsive Layouts)'
		        url = 'https://github.com/almondtools/fluent-allotropy'
	            licenses {
	                license {
			            name = 'GNU LESSER GENERAL PUBLIC LICENSE (LGPL)'
	        		    url = 'http://www.gnu.org/licenses/lgpl.txt'
	                }
	            }
	            developers {
	                developer {
			            id = 'amygdalum'
	        		    name = 'Stefan Mandel'
			            email = 'mail@amygdalum.net'
	                }
	            }
	            scm {
					connection = 'scm:git:git@github.com:almondtools/fluent-allotropy.git'
					developerConnection = 'scm:git:git@github.com:almondtools/fluent-allotropy.git'
					url = 'https://github.com/almondtools/fluent-allotropy'
	            }
	        }
        }
    }
}

signing {
    useGpgCmd()
    sign publishing.publications.mavenJava
}


tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

tasks.withType(Javadoc) {
    options.encoding = 'UTF-8'
    options.addBooleanOption('Xdoclint:none', true)
}